#!/usr/bin/env bash
set -euo pipefail

OPENVIKING_DIR="${OPENVIKING_HOME:-/root/.openviking}"
OV_CONF_PATH="${OPENVIKING_CONFIG_FILE:-${OPENVIKING_DIR}/ov.conf}"
OPENVIKING_WORKSPACE="${OPENVIKING_DIR}/data"

# ========== 用户可配置的环境变量 ==========
# Server
OPENVIKING_SERVER_HOST="${OPENVIKING_SERVER_HOST:-0.0.0.0}"
OPENVIKING_SERVER_PORT="${OPENVIKING_SERVER_PORT:-1933}"
OPENVIKING_ROOT_API_KEY="${OPENVIKING_ROOT_API_KEY:-}"

# Embedding (默认火山引擎)
OPENVIKING_EMBEDDING_PROVIDER="${OPENVIKING_EMBEDDING_PROVIDER:-volcengine}"
OPENVIKING_EMBEDDING_API_KEY="${OPENVIKING_EMBEDDING_API_KEY:-}"
OPENVIKING_EMBEDDING_API_BASE="${OPENVIKING_EMBEDDING_API_BASE:-https://ark.cn-beijing.volces.com/api/v3}"
OPENVIKING_EMBEDDING_MODEL="${OPENVIKING_EMBEDDING_MODEL:-doubao-embedding-vision-250615}"

# VLM (默认火山引擎)
OPENVIKING_VLM_PROVIDER="${OPENVIKING_VLM_PROVIDER:-volcengine}"
OPENVIKING_VLM_API_KEY="${OPENVIKING_VLM_API_KEY:-}"
OPENVIKING_VLM_API_BASE="${OPENVIKING_VLM_API_BASE:-https://ark.cn-beijing.volces.com/api/v3}"
OPENVIKING_VLM_MODEL="${OPENVIKING_VLM_MODEL:-doubao-seed-1-8-251228}"

# 是否强制重新生成配置
OPENVIKING_REGENERATE_CONFIG="${OPENVIKING_REGENERATE_CONFIG:-0}"

# ========== 内部默认值（不暴露） ==========
OPENVIKING_EMBEDDING_DIMENSION="1024"
OPENVIKING_EMBEDDING_INPUT="multimodal"
OPENVIKING_VLM_TEMPERATURE="0.1"
OPENVIKING_VLM_MAX_RETRIES="3"
OPENVIKING_VECTORDB_BACKEND="local"
OPENVIKING_AUTO_GENERATE_L0="false"
OPENVIKING_AUTO_GENERATE_L1="false"

mkdir -p "${OPENVIKING_DIR}" "${OPENVIKING_WORKSPACE}"

# 检查是否使用挂载的配置文件
if [[ -f "${OV_CONF_PATH}" && "${OPENVIKING_REGENERATE_CONFIG}" != "1" ]]; then
    echo "[INFO] Using mounted/existing config at ${OV_CONF_PATH}"
else
    # 需要生成配置
    if [[ -z "${OPENVIKING_EMBEDDING_API_KEY}" || -z "${OPENVIKING_VLM_API_KEY}" ]]; then
        echo "[ERROR] OPENVIKING_EMBEDDING_API_KEY and OPENVIKING_VLM_API_KEY are required."
        echo "[ERROR] Or mount your own ov.conf to ${OV_CONF_PATH}"
        exit 1
    fi

    # 导出所有变量供 envsubst 使用
    export OPENVIKING_SERVER_HOST OPENVIKING_SERVER_PORT OPENVIKING_ROOT_API_KEY OPENVIKING_WORKSPACE
    export OPENVIKING_EMBEDDING_PROVIDER OPENVIKING_EMBEDDING_API_KEY OPENVIKING_EMBEDDING_API_BASE
    export OPENVIKING_EMBEDDING_MODEL OPENVIKING_EMBEDDING_DIMENSION OPENVIKING_EMBEDDING_INPUT
    export OPENVIKING_VLM_PROVIDER OPENVIKING_VLM_API_KEY OPENVIKING_VLM_API_BASE
    export OPENVIKING_VLM_MODEL OPENVIKING_VLM_TEMPERATURE OPENVIKING_VLM_MAX_RETRIES
    export OPENVIKING_VECTORDB_BACKEND
    export OPENVIKING_AUTO_GENERATE_L0 OPENVIKING_AUTO_GENERATE_L1

    envsubst < /app/ov.conf.template.json > "${OV_CONF_PATH}"
    echo "[INFO] Generated OpenViking config at ${OV_CONF_PATH}"
fi

echo "[INFO] Starting OpenViking server on ${OPENVIKING_SERVER_HOST}:${OPENVIKING_SERVER_PORT}..."
exec python3 -m openviking.server.bootstrap --config "${OV_CONF_PATH}" --host "${OPENVIKING_SERVER_HOST}" --port "${OPENVIKING_SERVER_PORT}"
